# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/niclas/Documents/C++/ChessEngine/Odin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/niclas/Documents/C++/ChessEngine/Odin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/niclas/Documents/C++/ChessEngine/Odin/CMakeFiles /Users/niclas/Documents/C++/ChessEngine/Odin/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/niclas/Documents/C++/ChessEngine/Odin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Odin

# Build rule for target.
Odin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Odin
.PHONY : Odin

# fast build rule for target.
Odin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/build
.PHONY : Odin/fast

Odin/engine/Odin.o: Odin/engine/Odin.cpp.o

.PHONY : Odin/engine/Odin.o

# target to build an object file
Odin/engine/Odin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/engine/Odin.cpp.o
.PHONY : Odin/engine/Odin.cpp.o

Odin/engine/Odin.i: Odin/engine/Odin.cpp.i

.PHONY : Odin/engine/Odin.i

# target to preprocess a source file
Odin/engine/Odin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/engine/Odin.cpp.i
.PHONY : Odin/engine/Odin.cpp.i

Odin/engine/Odin.s: Odin/engine/Odin.cpp.s

.PHONY : Odin/engine/Odin.s

# target to generate assembly for a file
Odin/engine/Odin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/engine/Odin.cpp.s
.PHONY : Odin/engine/Odin.cpp.s

Odin/main.o: Odin/main.cpp.o

.PHONY : Odin/main.o

# target to build an object file
Odin/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/main.cpp.o
.PHONY : Odin/main.cpp.o

Odin/main.i: Odin/main.cpp.i

.PHONY : Odin/main.i

# target to preprocess a source file
Odin/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/main.cpp.i
.PHONY : Odin/main.cpp.i

Odin/main.s: Odin/main.cpp.s

.PHONY : Odin/main.s

# target to generate assembly for a file
Odin/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Odin.dir/build.make CMakeFiles/Odin.dir/Odin/main.cpp.s
.PHONY : Odin/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Odin"
	@echo "... Odin/engine/Odin.o"
	@echo "... Odin/engine/Odin.i"
	@echo "... Odin/engine/Odin.s"
	@echo "... Odin/main.o"
	@echo "... Odin/main.i"
	@echo "... Odin/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

